"""
Curated voice catalog across TTS providers.

Each voice is tagged with traits, use cases, and personality fit
based on real provider offerings and characteristics.
"""

from .models import (
    AgeRange, BrandPersonality, CostTier, Gender, LatencyTier,
    Provider, UseCase, Voice, VoiceTraits,
)

VOICES: list[Voice] = [
    # =========================================================================
    # CARTESIA - Sonic Turbo (fastest, streaming-first)
    # =========================================================================
    Voice(
        id="cartesia-british-lady",
        name="British Lady",
        provider=Provider.CARTESIA,
        provider_voice_id="79a125e8-cd45-4c13-8a67-188112f4dd22",
        gender=Gender.FEMALE,
        age_range=AgeRange.MIDDLE,
        accent="british",
        traits=VoiceTraits(warmth=0.6, energy=0.4, clarity=0.9, pace=0.5, authority=0.7, friendliness=0.5),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.FINANCE, UseCase.LEGAL, UseCase.HEALTHCARE],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.AUTHORITATIVE, BrandPersonality.TRUSTWORTHY],
        description="Polished British accent. Excellent for professional, trust-critical applications.",
    ),
    Voice(
        id="cartesia-california-girl",
        name="California Girl",
        provider=Provider.CARTESIA,
        provider_voice_id="b7d50908-b17c-442d-ad8d-7c56e5dd3cc6",
        gender=Gender.FEMALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.8, energy=0.8, clarity=0.7, pace=0.6, authority=0.2, friendliness=0.9),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.RETAIL, UseCase.FITNESS, UseCase.GENERAL],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.ENERGETIC, BrandPersonality.PLAYFUL],
        description="Upbeat, youthful energy. Great for casual consumer-facing products.",
    ),
    Voice(
        id="cartesia-midwestern-woman",
        name="Midwestern Woman",
        provider=Provider.CARTESIA,
        provider_voice_id="11af83e2-23eb-452f-956e-7fee218ccb99",
        gender=Gender.FEMALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.85, energy=0.4, clarity=0.8, pace=0.4, authority=0.4, friendliness=0.8),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.HEALTHCARE, UseCase.MENTAL_HEALTH, UseCase.CUSTOMER_SUPPORT],
        personality_fit=[BrandPersonality.EMPATHETIC, BrandPersonality.CALM, BrandPersonality.TRUSTWORTHY],
        description="Warm, steady, and reassuring. Ideal for healthcare and empathetic conversations.",
    ),
    Voice(
        id="cartesia-confident-man",
        name="Confident Man",
        provider=Provider.CARTESIA,
        provider_voice_id="a167e0f3-df7e-4d52-a9c3-f949145e0f0c",
        gender=Gender.MALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.5, energy=0.6, clarity=0.9, pace=0.5, authority=0.85, friendliness=0.4),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.SALES, UseCase.FINANCE, UseCase.REAL_ESTATE],
        personality_fit=[BrandPersonality.AUTHORITATIVE, BrandPersonality.PROFESSIONAL, BrandPersonality.TRUSTWORTHY],
        description="Strong, clear, and assertive. Built for sales and high-stakes conversations.",
    ),
    Voice(
        id="cartesia-friendly-man",
        name="Friendly Man",
        provider=Provider.CARTESIA,
        provider_voice_id="ee7ea9f8-c0c1-498c-9f62-dc2571ec235e",
        gender=Gender.MALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.8, energy=0.6, clarity=0.8, pace=0.5, authority=0.3, friendliness=0.85),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.TECH_SUPPORT, UseCase.EDUCATION, UseCase.CUSTOMER_SUPPORT],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.CALM, BrandPersonality.TRUSTWORTHY],
        description="Approachable and helpful. Natural fit for support and education.",
    ),
    Voice(
        id="cartesia-sweet-lady",
        name="Sweet Lady",
        provider=Provider.CARTESIA,
        provider_voice_id="e3827ec5-697a-4b7c-9c82-4a5c5e2f5b8d",
        gender=Gender.FEMALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.9, energy=0.5, clarity=0.75, pace=0.45, authority=0.2, friendliness=0.9),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.MENTAL_HEALTH, UseCase.HEALTHCARE, UseCase.HOSPITALITY],
        personality_fit=[BrandPersonality.EMPATHETIC, BrandPersonality.FRIENDLY, BrandPersonality.CALM],
        description="Gentle and nurturing. Perfect for mental health, care check-ins.",
    ),
    Voice(
        id="cartesia-southern-gentleman",
        name="Southern Gentleman",
        provider=Provider.CARTESIA,
        provider_voice_id="98a34ef2-2140-4c28-9c71-663dc4dd7022",
        gender=Gender.MALE,
        age_range=AgeRange.MATURE,
        accent="american",
        traits=VoiceTraits(warmth=0.85, energy=0.3, clarity=0.75, pace=0.35, authority=0.6, friendliness=0.7),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.HOSPITALITY, UseCase.REAL_ESTATE, UseCase.GENERAL],
        personality_fit=[BrandPersonality.TRUSTWORTHY, BrandPersonality.CALM, BrandPersonality.LUXURIOUS],
        description="Warm, unhurried Southern charm. Great for hospitality and premium brands.",
    ),

    # =========================================================================
    # ELEVENLABS - Highest quality, most natural
    # =========================================================================
    Voice(
        id="eleven-rachel",
        name="Rachel",
        provider=Provider.ELEVENLABS,
        provider_voice_id="21m00Tcm4TlvDq8ikWAM",
        gender=Gender.FEMALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.7, energy=0.5, clarity=0.9, pace=0.5, authority=0.6, friendliness=0.6),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.HIGH,
        best_for=[UseCase.GENERAL, UseCase.EDUCATION, UseCase.CUSTOMER_SUPPORT],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.TRUSTWORTHY, BrandPersonality.FRIENDLY],
        description="Versatile, natural-sounding. ElevenLabs flagship voice. Works across many use cases.",
    ),
    Voice(
        id="eleven-josh",
        name="Josh",
        provider=Provider.ELEVENLABS,
        provider_voice_id="TxGEqnHWrfWFTfGW9XjX",
        gender=Gender.MALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.65, energy=0.6, clarity=0.85, pace=0.5, authority=0.5, friendliness=0.7),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.HIGH,
        best_for=[UseCase.EDUCATION, UseCase.TECH_SUPPORT, UseCase.GENERAL],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.PROFESSIONAL, BrandPersonality.TRUSTWORTHY],
        description="Young professional male. Clear and engaging, great for explanations.",
    ),
    Voice(
        id="eleven-dorothy",
        name="Dorothy",
        provider=Provider.ELEVENLABS,
        provider_voice_id="ThT5KcBeYPX3keUQqHPh",
        gender=Gender.FEMALE,
        age_range=AgeRange.YOUNG,
        accent="british",
        traits=VoiceTraits(warmth=0.75, energy=0.5, clarity=0.8, pace=0.45, authority=0.4, friendliness=0.8),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.HIGH,
        best_for=[UseCase.HOSPITALITY, UseCase.RETAIL, UseCase.EDUCATION],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.LUXURIOUS, BrandPersonality.CALM],
        description="Warm British voice with a pleasant, approachable quality. Premium feel.",
    ),
    Voice(
        id="eleven-adam",
        name="Adam",
        provider=Provider.ELEVENLABS,
        provider_voice_id="pNInz6obpgDQGcFmaJgB",
        gender=Gender.MALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.5, energy=0.5, clarity=0.9, pace=0.5, authority=0.8, friendliness=0.4),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.HIGH,
        best_for=[UseCase.FINANCE, UseCase.LEGAL, UseCase.SALES],
        personality_fit=[BrandPersonality.AUTHORITATIVE, BrandPersonality.PROFESSIONAL, BrandPersonality.TRUSTWORTHY],
        description="Deep, authoritative male voice. Commands attention and trust.",
    ),
    Voice(
        id="eleven-bella",
        name="Bella",
        provider=Provider.ELEVENLABS,
        provider_voice_id="EXAVITQu4vr4xnSDxMaL",
        gender=Gender.FEMALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.85, energy=0.55, clarity=0.8, pace=0.5, authority=0.3, friendliness=0.85),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.HIGH,
        best_for=[UseCase.MENTAL_HEALTH, UseCase.HEALTHCARE, UseCase.CUSTOMER_SUPPORT],
        personality_fit=[BrandPersonality.EMPATHETIC, BrandPersonality.FRIENDLY, BrandPersonality.CALM],
        description="Soft, empathetic, caring. Excellent for sensitive conversations.",
    ),

    # =========================================================================
    # DEEPGRAM AURA - Low latency, cost effective
    # =========================================================================
    Voice(
        id="deepgram-asteria",
        name="Asteria",
        provider=Provider.DEEPGRAM,
        provider_voice_id="aura-asteria-en",
        gender=Gender.FEMALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.65, energy=0.5, clarity=0.85, pace=0.5, authority=0.5, friendliness=0.6),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.LOW,
        best_for=[UseCase.CUSTOMER_SUPPORT, UseCase.GENERAL, UseCase.TECH_SUPPORT],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.FRIENDLY, BrandPersonality.TRUSTWORTHY],
        description="Balanced female voice. Best value for high-volume deployments.",
    ),
    Voice(
        id="deepgram-orion",
        name="Orion",
        provider=Provider.DEEPGRAM,
        provider_voice_id="aura-orion-en",
        gender=Gender.MALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.55, energy=0.5, clarity=0.85, pace=0.5, authority=0.65, friendliness=0.5),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.LOW,
        best_for=[UseCase.CUSTOMER_SUPPORT, UseCase.TECH_SUPPORT, UseCase.GENERAL],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.AUTHORITATIVE, BrandPersonality.TRUSTWORTHY],
        description="Clear male voice. Reliable workhorse for support and info delivery.",
    ),
    Voice(
        id="deepgram-luna",
        name="Luna",
        provider=Provider.DEEPGRAM,
        provider_voice_id="aura-luna-en",
        gender=Gender.FEMALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.75, energy=0.6, clarity=0.8, pace=0.55, authority=0.3, friendliness=0.8),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.LOW,
        best_for=[UseCase.RETAIL, UseCase.GENERAL, UseCase.EDUCATION],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.ENERGETIC, BrandPersonality.PLAYFUL],
        description="Bright, friendly female voice. Good for consumer-facing at scale.",
    ),
    Voice(
        id="deepgram-arcas",
        name="Arcas",
        provider=Provider.DEEPGRAM,
        provider_voice_id="aura-arcas-en",
        gender=Gender.MALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.7, energy=0.55, clarity=0.8, pace=0.5, authority=0.4, friendliness=0.7),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.LOW,
        best_for=[UseCase.EDUCATION, UseCase.TECH_SUPPORT, UseCase.GENERAL],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.CALM, BrandPersonality.TRUSTWORTHY],
        description="Youthful male voice. Approachable and easy to listen to.",
    ),

    # =========================================================================
    # OPENAI TTS
    # =========================================================================
    Voice(
        id="openai-alloy",
        name="Alloy",
        provider=Provider.OPENAI,
        provider_voice_id="alloy",
        gender=Gender.NEUTRAL,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.6, energy=0.5, clarity=0.85, pace=0.5, authority=0.5, friendliness=0.6),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.GENERAL, UseCase.TECH_SUPPORT, UseCase.EDUCATION],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.FRIENDLY, BrandPersonality.TRUSTWORTHY],
        description="Gender-neutral, versatile. Safe default for diverse audiences.",
    ),
    Voice(
        id="openai-nova",
        name="Nova",
        provider=Provider.OPENAI,
        provider_voice_id="nova",
        gender=Gender.FEMALE,
        age_range=AgeRange.YOUNG,
        accent="american",
        traits=VoiceTraits(warmth=0.75, energy=0.65, clarity=0.85, pace=0.55, authority=0.35, friendliness=0.8),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.RETAIL, UseCase.CUSTOMER_SUPPORT, UseCase.GENERAL],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.ENERGETIC, BrandPersonality.PLAYFUL],
        description="Bright and engaging female voice. Great for consumer apps.",
    ),
    Voice(
        id="openai-onyx",
        name="Onyx",
        provider=Provider.OPENAI,
        provider_voice_id="onyx",
        gender=Gender.MALE,
        age_range=AgeRange.MATURE,
        accent="american",
        traits=VoiceTraits(warmth=0.45, energy=0.4, clarity=0.9, pace=0.45, authority=0.85, friendliness=0.35),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.FINANCE, UseCase.LEGAL, UseCase.SALES],
        personality_fit=[BrandPersonality.AUTHORITATIVE, BrandPersonality.PROFESSIONAL, BrandPersonality.LUXURIOUS],
        description="Deep, commanding male voice. Premium, executive-level feel.",
    ),
    Voice(
        id="openai-shimmer",
        name="Shimmer",
        provider=Provider.OPENAI,
        provider_voice_id="shimmer",
        gender=Gender.FEMALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.8, energy=0.45, clarity=0.8, pace=0.45, authority=0.4, friendliness=0.75),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.HEALTHCARE, UseCase.MENTAL_HEALTH, UseCase.HOSPITALITY],
        personality_fit=[BrandPersonality.EMPATHETIC, BrandPersonality.CALM, BrandPersonality.TRUSTWORTHY],
        description="Warm, soothing female voice. Well-suited for care and wellness.",
    ),
    Voice(
        id="openai-echo",
        name="Echo",
        provider=Provider.OPENAI,
        provider_voice_id="echo",
        gender=Gender.MALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.6, energy=0.5, clarity=0.85, pace=0.5, authority=0.6, friendliness=0.55),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.EDUCATION, UseCase.GENERAL, UseCase.TECH_SUPPORT],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.TRUSTWORTHY, BrandPersonality.CALM],
        description="Balanced male voice. Reliable and easy to listen to for long sessions.",
    ),

    # =========================================================================
    # PLAYHT
    # =========================================================================
    Voice(
        id="playht-jennifer",
        name="Jennifer",
        provider=Provider.PLAYHT,
        provider_voice_id="jennifer",
        gender=Gender.FEMALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.7, energy=0.5, clarity=0.85, pace=0.5, authority=0.55, friendliness=0.65),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.CUSTOMER_SUPPORT, UseCase.HEALTHCARE, UseCase.GENERAL],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.FRIENDLY, BrandPersonality.TRUSTWORTHY],
        description="Polished and warm. Strong all-rounder for professional use cases.",
    ),
    Voice(
        id="playht-michael",
        name="Michael",
        provider=Provider.PLAYHT,
        provider_voice_id="michael",
        gender=Gender.MALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.55, energy=0.55, clarity=0.9, pace=0.5, authority=0.7, friendliness=0.5),
        latency_tier=LatencyTier.FAST,
        cost_tier=CostTier.MEDIUM,
        best_for=[UseCase.SALES, UseCase.FINANCE, UseCase.REAL_ESTATE],
        personality_fit=[BrandPersonality.AUTHORITATIVE, BrandPersonality.PROFESSIONAL, BrandPersonality.TRUSTWORTHY],
        description="Confident, clear male voice. Strong for sales and advisory.",
    ),

    # =========================================================================
    # RIME - Ultra low latency
    # =========================================================================
    Voice(
        id="rime-marsh",
        name="Marsh",
        provider=Provider.RIME,
        provider_voice_id="marsh",
        gender=Gender.MALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.6, energy=0.5, clarity=0.85, pace=0.5, authority=0.6, friendliness=0.55),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.LOW,
        best_for=[UseCase.CUSTOMER_SUPPORT, UseCase.TECH_SUPPORT, UseCase.GENERAL],
        personality_fit=[BrandPersonality.PROFESSIONAL, BrandPersonality.CALM, BrandPersonality.TRUSTWORTHY],
        description="Clean, fast male voice. Excellent for latency-critical deployments.",
    ),
    Voice(
        id="rime-bayou",
        name="Bayou",
        provider=Provider.RIME,
        provider_voice_id="bayou",
        gender=Gender.FEMALE,
        age_range=AgeRange.MIDDLE,
        accent="american",
        traits=VoiceTraits(warmth=0.7, energy=0.45, clarity=0.8, pace=0.45, authority=0.45, friendliness=0.7),
        latency_tier=LatencyTier.FASTEST,
        cost_tier=CostTier.LOW,
        best_for=[UseCase.CUSTOMER_SUPPORT, UseCase.HEALTHCARE, UseCase.GENERAL],
        personality_fit=[BrandPersonality.FRIENDLY, BrandPersonality.CALM, BrandPersonality.EMPATHETIC],
        description="Warm female voice with low latency. Good for care-oriented agents.",
    ),
]


def get_voices_by_provider(provider: Provider) -> list[Voice]:
    return [v for v in VOICES if v.provider == provider]


def get_voices_by_use_case(use_case: UseCase) -> list[Voice]:
    return [v for v in VOICES if use_case in v.best_for]
